export const CLEAR_STATUS = 'CLEAR_STATUS';
export const ADD_RULE_SUCCESS = 'ADD_RULE_SUCCESS';
export const ADD_RULE_ERR = 'ADD_RULE_ERR';
export const REMOVE_RULE = 'REMOVE_RULE';
export const EXECUTE_FLOW = 'EXECUTE_FLOW';
export const EXECUTE_FLOW_ERR = 'EXECUTE_FLOW_ERR';
